spring.application.name=helpDesk

spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.validate-migration-naming=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
jwt.secret =Aw87T0dZQ82kMFi/OSc8RtrDtXg2YVVb5DiRxYvV/Hs=
logging.level.org.springframework.security=DEBUG