
create table attachments (
                             attachment_id bigint generated by default as identity,
                             created_at timestamp(6) with time zone not null,
                             note_id bigint,
                             ticket_id bigint,
                             updated_at timestamp(6) with time zone not null,
                             title varchar(50) not null,
                             description varchar(255),
                             url varchar(255),
                             primary key (attachment_id)
);

create table comments (
                          comment_id bigint generated by default as identity,
                          created_at timestamp(6) with time zone not null,
                          ticket_id bigint not null,
                          user_id bigint,
                          description varchar(255),
                          primary key (comment_id)
);

create table notes (
                       created_at timestamp(6) with time zone not null,
                       note_id bigint generated by default as identity,
                       ticket_id bigint not null,
                       updated_at timestamp(6) with time zone not null,
                       user_id bigint,
                       description varchar(255),
                       primary key (note_id)
);

create table notifications (
                               created_at timestamp(6) with time zone not null,
                               notification_id bigint generated by default as identity,
                               read_at timestamp(6) with time zone,
                               target_role bigint,
                               target_user bigint,
                               updated_at timestamp(6) with time zone not null,
                               title varchar(60) not null,
                               description text,
                               primary key (notification_id)
);

create table permissions (
                             permission_id bigint generated by default as identity,
                             name varchar(60) not null,
                             description varchar(255),
                             primary key (permission_id)
);

create table priorities (
                            priority_id bigint generated by default as identity,
                            name varchar(60) not null unique,
                            description varchar(255),
                            primary key (priority_id)
);

create table role_permission_junction (
                                          permission_id bigint not null,
                                          role_id bigint not null,
                                          primary key (permission_id, role_id)
);

create table roles (
                       role_id bigint generated by default as identity,
                       name varchar(80) not null,
                       description varchar(255),
                       primary key (role_id)
);

create table sla_policies (
                              policy_id bigint generated by default as identity,
                              priority_id bigint not null,
                              resolution_time interval second(6) not null,
                              response_time interval second(6) not null,
                              description varchar(255),
                              primary key (policy_id)
);

create table ticket_activities (
                                   activity_id bigint generated by default as identity,
                                   created_at timestamp(6) with time zone not null,
                                   ticket_id bigint,
                                   user_id bigint,
                                   description varchar(255),
                                   primary key (activity_id)
);

create table ticket_categories (
                                   category_id bigint generated by default as identity,
                                   name varchar(80) not null unique,
                                   description varchar(255),
                                   primary key (category_id)
);

create table ticket_assignment (
                                   is_active boolean not null,
                                   assigned_at timestamp(6) with time zone,
                                   assigned_by_user_id bigint,
                                   assigned_to_user_id bigint,
                                   assignment_id bigint generated by default as identity,
                                   created_at timestamp(6) with time zone not null,
                                   ticket_id bigint,
                                   updated_at timestamp(6) with time zone not null,
                                   primary key (assignment_id)
);

create table tickets (
                         category_id bigint,
                         created_at timestamp(6) with time zone not null,
                         requestor_id bigint,
                         resolution_deadline timestamp(6) with time zone not null,
                         response_deadline timestamp(6) with time zone not null,
                         ticket_id bigint generated by default as identity,
                         ticket_priority_id bigint,
                         updated_at timestamp(6) with time zone not null,
                         ticket_public_id uuid not null unique,
                         title varchar(80) not null,
                         description varchar(255),
                         status varchar(255) not null check ((status in ('OPEN','IN_PROGRESS','WAITING_ON_REQUESTOR','RESOLVED','CLOSED'))),
                         primary key (ticket_id)
);

create table users (
                       is_active boolean default true not null,
                       created_at timestamp(6) with time zone not null,
                       role_id bigint,
                       updated_at timestamp(6) with time zone not null,
                       user_id bigint generated by default as identity,
                       user_public_id uuid not null unique,
                       email varchar(255) not null,
                       name varchar(255) not null,
                       password varchar(255) not null unique,
                       primary key (user_id)
);

create index idx_attachments_ticket_id
    on attachments (ticket_id);

create index idx_attachments_notes_id
    on attachments (note_id);

create index idx_comment_ticket_id
    on comments (ticket_id);

create index idx_ticket_activities_ticket_id
    on ticket_activities (ticket_id);

create index idx_index_requestor
    on tickets (requestor_id);

create index idx_ticket_category_id
    on tickets (category_id);

create index idx_ticket_priority_id
    on tickets (ticket_priority_id);

alter table if exists attachments
    add constraint FKada67pertq4gnntow8284gvpt
    foreign key (note_id)
    references notes;

alter table if exists attachments
    add constraint FKay82o4g9v0hkdlh20yllwvutc
    foreign key (ticket_id)
    references tickets;

alter table if exists comments
    add constraint FKj7vc0aigr2m5mew52v7ddt4fo
    foreign key (ticket_id)
    references tickets;

alter table if exists comments
    add constraint FK8omq0tc18jd43bu5tjh6jvraq
    foreign key (user_id)
    references users;

alter table if exists notes
    add constraint FK6t6b86e5gjrpg2rx5if0ikudf
    foreign key (ticket_id)
    references tickets;

alter table if exists notes
    add constraint FKechaouoa6kus6k1dpix1u91c
    foreign key (user_id)
    references users;

alter table if exists notifications
    add constraint FK6tescsbtqdjoxx3r3gbnhdh7j
    foreign key (target_role)
    references roles;

alter table if exists notifications
    add constraint FKr2sdtqhekfaiv12syik6p4393
    foreign key (target_user)
    references users;

alter table if exists role_permission_junction
    add constraint FKd6ldv3a774tne9cx44uhu4cjd
    foreign key (permission_id)
    references permissions;

alter table if exists role_permission_junction
    add constraint FK3dsvkywx5ylpd2uc1quq84lgg
    foreign key (role_id)
    references roles;

alter table if exists sla_policies
    add constraint FKo3nastjbdxw5ismwwff8c0ge8
    foreign key (priority_id)
    references priorities;

alter table if exists ticket_activities
    add constraint FKdhij2mdyeye32j67hwfe6wytu
    foreign key (ticket_id)
    references tickets;

alter table if exists ticket_activities
    add constraint FKd8ugmdooog66nah1hsil9ajai
    foreign key (user_id)
    references users;

alter table if exists ticket_assignment
    add constraint FKowrm3p8oum32tn1t374q1kp3
    foreign key (assigned_by_user_id)
    references users;

alter table if exists ticket_assignment
    add constraint FKkikv4tfa9g4snaenp1jqdl4eu
    foreign key (assigned_to_user_id)
    references users;

alter table if exists ticket_assignment
    add constraint FKqxxeuopn69n3tlrvn4p87flim
    foreign key (ticket_id)
    references tickets;

alter table if exists tickets
    add constraint FKv3rpsd50yy4waw8na87e3a1u
    foreign key (category_id)
    references ticket_categories;

alter table if exists tickets
    add constraint FK9ox7v58efdcc79y7g0bpn3sqy
    foreign key (requestor_id)
    references users;

alter table if exists tickets
    add constraint FKgng47to5koib53pg440gsgcln
    foreign key (ticket_priority_id)
    references priorities;

alter table if exists users
    add constraint FKp56c1712k691lhsyewcssf40f
    foreign key (role_id)
    references roles;

