CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "users" (
                         "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "user_public_id" UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
                         "email" VARCHAR(60) UNIQUE NOT NULL,
                         "name" VARCHAR(60) NOT NULL,
                         "password" VARCHAR NOT NULL,
                         "role_id" BIGINT,
                         "is_active" BOOLEAN NOT NULL DEFAULT true,
                         "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                         "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE "roles" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" VARCHAR(60) UNIQUE NOT NULL,
                         "description" VARCHAR
);


CREATE TABLE "permissions" (
                               "permission_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "name" VARCHAR(60) UNIQUE NOT NULL,
                               "description" VARCHAR
);


CREATE TABLE "ticket_categories" (
                                     "category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "name" VARCHAR(60) UNIQUE NOT NULL,
                                     "description" VARCHAR
);


CREATE TABLE "priorities" (
                              "priority_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" VARCHAR(60) UNIQUE NOT NULL,
                              "description" VARCHAR
);


CREATE TABLE "tickets" (
                           "ticket_public_id" UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
                           "ticket_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "title" VARCHAR(60) NOT NULL,
                           "description" VARCHAR,
                           "category_id" BIGINT NOT NULL,
                           "priority_id" BIGINT NOT NULL,
                           "requestor" BIGINT NOT NULL,
                           "status" VARCHAR(30) NOT NULL CHECK (
                               "status" IN (
                                            'OPEN',
                                            'IN_PROGRESS',
                                            'WAITING_ON_REQUESTER',
                                            'RESOLVED',
                                            'CLOSED'
                                   )
                               ),
                           "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                           "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()  ,
                           "response_deadline" TIMESTAMPTZ,
                           "resolution_deadline" TIMESTAMPTZ

);


CREATE TABLE "sla_policies" (
                                "policy_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "priority_id" BIGINT UNIQUE NOT NULL,
                                "description" VARCHAR,
                                "response_time" INTERVAL NOT NULL
    CHECK ("response_time" > INTERVAL '0 seconds'),
                                "resolution_time" INTERVAL NOT NULL
    CHECK ("resolution_time" > INTERVAL '0 seconds')
);


CREATE TABLE "comments" (
                            "comment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "user_id" BIGINT NOT NULL,
                            "comment_description" VARCHAR,
                            "ticket_id" BIGINT NOT NULL,
                            "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE "ticket_activities" (
                                     "activity_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "description" VARCHAR,
                                     "user_id" BIGINT NOT NULL,
                                     "ticket_id" BIGINT NOT NULL,
                                     "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE "ticket_assignment" (
                                     "assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "assigned_by" BIGINT NOT NULL,
                                     "assigned_to" BIGINT NOT NULL,
                                     "ticket_id" BIGINT NOT NULL,
                                     "is_active" BOOLEAN NOT NULL DEFAULT true,
                                     "unassigned_at" TIMESTAMPTZ,
                                     "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                     "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE "notes" (
                         "notes_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "user_id" BIGINT NOT NULL,
                         "description" VARCHAR,
                         "ticket_id" BIGINT NOT NULL,
                         "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                         "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE "attachments" (
                               "attachment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "title" VARCHAR NOT NULL,
                               "description" VARCHAR,
                               "url" VARCHAR NOT NULL,
                               "ticket_id" BIGINT,
                               "notes_id" BIGINT,
                               "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                               "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

                               CONSTRAINT "attachments_owner_xor" CHECK (
                                   (
                                       "ticket_id" IS NOT NULL
                                           AND "notes_id" IS NULL
                                       )
                                       OR
                                   (
                                       "ticket_id" IS NULL
                                           AND "notes_id" IS NOT NULL
                                       )
                                   )
);


CREATE TABLE "notifications" (
                                 "notification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "title" VARCHAR(60) NOT NULL,
                                 "description" VARCHAR,
                                 "read_at" TIMESTAMPTZ,
                                 "target_user" BIGINT,
                                 "target_role" BIGINT,
                                 "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE "role_permission_junction" (
                                            "role_id" BIGINT NOT NULL,
                                            "permission_id" BIGINT NOT NULL,

                                            PRIMARY KEY ("role_id", "permission_id")
);


CREATE INDEX "idx_users_role_id"
    ON "users" ("role_id");


CREATE INDEX "idx_tickets_requestor"
    ON "tickets" ("requestor");

CREATE INDEX "idx_tickets_category_id"
    ON "tickets" ("category_id");

CREATE INDEX "idx_tickets_priority_id"
    ON "tickets" ("priority_id");


CREATE INDEX "idx_comments_ticket_id"
    ON "comments" ("ticket_id");


CREATE INDEX "idx_ticket_activities_ticket_id"
    ON "ticket_activities" ("ticket_id");


CREATE INDEX "idx_ticket_assignment_ticket_id"
    ON "ticket_assignment" ("ticket_id");

CREATE INDEX "idx_ticket_assignment_active"
    ON "ticket_assignment" ("ticket_id")
    WHERE "is_active" = true;


CREATE INDEX "idx_notes_ticket_id"
    ON "notes" ("ticket_id");


CREATE INDEX "idx_attachments_ticket_id"
    ON "attachments" ("ticket_id");

CREATE INDEX "idx_attachments_notes_id"
    ON "attachments" ("notes_id");


CREATE INDEX "idx_notifications_target_user"
    ON "notifications" ("target_user");

CREATE INDEX "idx_notifications_target_role"
    ON "notifications" ("target_role");

CREATE INDEX "idx_notifications_target_user_unread"
    ON "notifications" ("target_user")
    WHERE "read_at" IS NULL;


ALTER TABLE "users"
    ADD FOREIGN KEY ("role_id")
        REFERENCES "roles" ("id");


ALTER TABLE "role_permission_junction"
    ADD FOREIGN KEY ("role_id")
        REFERENCES "roles" ("id")
        ON DELETE CASCADE;

ALTER TABLE "role_permission_junction"
    ADD FOREIGN KEY ("permission_id")
        REFERENCES "permissions" ("permission_id")
        ON DELETE CASCADE;


ALTER TABLE "comments"
    ADD FOREIGN KEY ("user_id")
        REFERENCES "users" ("user_id");

ALTER TABLE "comments"
    ADD FOREIGN KEY ("ticket_id")
        REFERENCES "tickets" ("ticket_id")
        ON DELETE CASCADE;


ALTER TABLE "ticket_activities"
    ADD FOREIGN KEY ("user_id")
        REFERENCES "users" ("user_id");

ALTER TABLE "ticket_activities"
    ADD FOREIGN KEY ("ticket_id")
        REFERENCES "tickets" ("ticket_id")
        ON DELETE CASCADE;


ALTER TABLE "tickets"
    ADD FOREIGN KEY ("requestor")
        REFERENCES "users" ("user_id");

ALTER TABLE "tickets"
    ADD FOREIGN KEY ("category_id")
        REFERENCES "ticket_categories" ("category_id");

ALTER TABLE "tickets"
    ADD FOREIGN KEY ("priority_id")
        REFERENCES "priorities" ("priority_id");


ALTER TABLE "sla_policies"
    ADD FOREIGN KEY ("priority_id")
        REFERENCES "priorities" ("priority_id");


ALTER TABLE "ticket_assignment"
    ADD FOREIGN KEY ("assigned_by")
        REFERENCES "users" ("user_id");

ALTER TABLE "ticket_assignment"
    ADD FOREIGN KEY ("assigned_to")
        REFERENCES "users" ("user_id");

ALTER TABLE "ticket_assignment"
    ADD FOREIGN KEY ("ticket_id")
        REFERENCES "tickets" ("ticket_id")
        ON DELETE CASCADE;


ALTER TABLE "notes"
    ADD FOREIGN KEY ("user_id")
        REFERENCES "users" ("user_id");

ALTER TABLE "notes"
    ADD FOREIGN KEY ("ticket_id")
        REFERENCES "tickets" ("ticket_id")
        ON DELETE CASCADE;


ALTER TABLE "attachments"
    ADD FOREIGN KEY ("ticket_id")
        REFERENCES "tickets" ("ticket_id")
        ON DELETE CASCADE;

ALTER TABLE "attachments"
    ADD FOREIGN KEY ("notes_id")
        REFERENCES "notes" ("notes_id")
        ON DELETE CASCADE;


ALTER TABLE "notifications"
    ADD FOREIGN KEY ("target_user")
        REFERENCES "users" ("user_id");

ALTER TABLE "notifications"
    ADD FOREIGN KEY ("target_role")
        REFERENCES "roles" ("id");


CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW."updated_at" = now();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER "set_users_updated_at"
    BEFORE UPDATE ON "users"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER "set_ticket_assignment_updated_at"
    BEFORE UPDATE ON "ticket_assignment"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER "set_notifications_updated_at"
    BEFORE UPDATE ON "notifications"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER "set_attachments_updated_at"
    BEFORE UPDATE ON "attachments"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER "set_notes_updated_at"
    BEFORE UPDATE ON "notes"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER "set_tickets_updated_at"
    BEFORE UPDATE ON "tickets"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();